config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :professors

      resources :posts

      resources :users

      resources :courses
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "courses#index"
  resources :professors
  resources :posts
  resources :users
  resources :courses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
  # Direct associations

  has_many   :posts,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/professors_controller.rb
class Api::V1::ProfessorsController < Api::V1::GraphitiController
  def index
    professors = ProfessorResource.all(params)
    respond_with(professors)
  end

  def show
    professor = ProfessorResource.find(params)
    respond_with(professor)
  end

  def create
    professor = ProfessorResource.build(params)

    if professor.save
      render jsonapi: professor, status: :created
    else
      render jsonapi_errors: professor
    end
  end

  def update
    professor = ProfessorResource.find(params)

    if professor.update_attributes
      render jsonapi: professor
    else
      render jsonapi_errors: professor
    end
  end

  def destroy
    professor = ProfessorResource.find(params)

    if professor.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: professor
    end
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: %i[show edit update destroy]

  def index
    @q = Professor.ransack(params[:q])
    @professors = @q.result(distinct: true).includes(:posts).page(params[:page]).per(10)
  end

  def show
    @post = Post.new
  end

  def new
    @professor = Professor.new
  end

  def edit; end

  def create
    @professor = Professor.new(professor_params)

    if @professor.save
      redirect_to @professor, notice: "Professor was successfully created."
    else
      render :new
    end
  end

  def update
    if @professor.update(professor_params)
      redirect_to @professor, notice: "Professor was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @professor.destroy
    redirect_to professors_url, notice: "Professor was successfully destroyed."
  end

  private

  def set_professor
    @professor = Professor.find(params[:id])
  end

  def professor_params
    params.require(:professor).permit(:name, :profile_url)
  end
end

app/views/professors/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Professor #<%= professor.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= professor.name %></dd>

      <dt>Profile url</dt>
      <dd><%= professor.profile_url %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back professor, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_professor_url(professor), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to professor, method: :delete, data: { confirm: "Do you really want to delete this professor?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(professor.updated_at) %> ago
  </div>
</div>

app/views/professors/_form.html.erb
<% was_validated = professor.errors.any? %>

<%= form_with(model: professor, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = professor.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% professor.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% profile_url_class = "form-control" %>
    <% profile_url_was_invalid = professor.errors.include?(:profile_url) %>

    <% if was_validated %>
      <% if profile_url_was_invalid %>
        <% profile_url_class << " is-invalid" %>
      <% else %>
        <% profile_url_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :profile_url %>
    <%= f.text_field :profile_url, class: profile_url_class, placeholder: "Enter profile url" %>
    <% if profile_url_was_invalid %>
      <% professor.errors.full_messages_for(:profile_url).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/professors/_list_item.html.erb
<%= link_to professor, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= professor %>
    <small class="text-muted">
      <%= time_ago_in_words(professor.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/professors/_professor_posts.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Posts

    <a data-toggle="collapse" href="#professor_posts_new_form">
      Add post
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @professor.posts.each do |post| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to post, post %>

        <%= link_to post, method: :delete, data: { confirm: "Do you really want to delete this post" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="professor_posts_new_form">
        <%= render partial: "professors/professor_posts_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/professors/_professor_posts_new_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :rating %>

    <%= f.text_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :poster_id %>

    <%= f.collection_select :poster_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :course_id %>

    <%= f.collection_select :course_id, Course.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :professor_id, value: @professor.id %>

  <%= f.submit "Create post", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/professors/_professors_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "professors_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :profile_url_cont, "Profile url contains" %>
    <%= f.text_field :profile_url_cont, :class => "form-control", :placeholder => "Profile url contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :rating, "Post Rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :posts_rating_gteq, :class => "form-control", :placeholder => "Post Rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :posts_rating_lteq, :class => "form-control", :placeholder => "Post Rating less than or equal to" %>
      </div>
    </div>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/professors" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#professors_filters">
  Show filters
</a>

app/views/professors/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Professor #<%= @professor.id %>
      </h2>

      <div class="card-body">
        <%= render "form", professor: @professor %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/professors/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Professors

      <%= link_to new_professor_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "professors/professors_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Professors

        <%= link_to new_professor_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @professors, partial: "list_item", as: :professor %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @professors, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/professors/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Professor
      </h2>

      <div class="card-body">
        <%= render "form", professor: @professor %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/professors/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @professor, partial: "card", as: :professor %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "professors/professor_posts" %>
  </div>
</div>