config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :professors

      resources :posts

      resources :users

      resources :courses
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "courses#index"
  resources :professors
  resources :posts
  resources :users
  resources :courses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # Direct associations

  belongs_to :professor

  belongs_to :poster,
             class_name: "User"

  belongs_to :course

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    rating
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::GraphitiController
  def index
    posts = PostResource.all(params)
    respond_with(posts)
  end

  def show
    post = PostResource.find(params)
    respond_with(post)
  end

  def create
    post = PostResource.build(params)

    if post.save
      render jsonapi: post, status: :created
    else
      render jsonapi_errors: post
    end
  end

  def update
    post = PostResource.find(params)

    if post.update_attributes
      render jsonapi: post
    else
      render jsonapi_errors: post
    end
  end

  def destroy
    post = PostResource.find(params)

    if post.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: post
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:course, :poster,
                                                :professor).page(params[:page]).per(10)
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)

    if @post.save
      message = "Post was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @post, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    message = "Post was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to posts_url, notice: message
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:rating, :poster_id, :course_id,
                                 :professor_id)
  end
end

app/views/posts/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Post #<%= post.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Rating</dt>
      <dd><%= post.rating %></dd>

      <dt>Poster</dt>
      <dd>
        <% if @post.poster.present? %>
          <%= link_to post.poster, post.poster %>
        <% end %>
      </dd>

      <dt>Course</dt>
      <dd>
        <% if @post.course.present? %>
          <%= link_to post.course, post.course %>
        <% end %>
      </dd>

      <dt>Professor</dt>
      <dd>
        <% if @post.professor.present? %>
          <%= link_to post.professor, post.professor %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back post, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_post_url(post), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to post, method: :delete, data: { confirm: "Do you really want to delete this post?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(post.updated_at) %> ago
  </div>
</div>

app/views/posts/_form.html.erb
<% was_validated = post.errors.any? %>

<%= form_with(model: post, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% rating_class = "form-control" %>
    <% rating_was_invalid = post.errors.include?(:rating) %>

    <% if was_validated %>
      <% if rating_was_invalid %>
        <% rating_class << " is-invalid" %>
      <% else %>
        <% rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :rating %>
    <%= f.number_field :rating, class: rating_class, placeholder: "Enter rating" %>
    <% if rating_was_invalid %>
      <% post.errors.full_messages_for(:rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% poster_class = "form-control" %>
    <% poster_was_invalid = post.errors.include?(:poster) %>

    <% if was_validated %>
      <% if poster_was_invalid %>
        <% poster_class << " is-invalid" %>
      <% else %>
        <% poster_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :poster_id %>
    <%= f.collection_select :poster_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if poster_was_invalid %>
      <% post.errors.full_messages_for(:poster).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% course_class = "form-control" %>
    <% course_was_invalid = post.errors.include?(:course) %>

    <% if was_validated %>
      <% if course_was_invalid %>
        <% course_class << " is-invalid" %>
      <% else %>
        <% course_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :course_id %>
    <%= f.collection_select :course_id, Course.all, :id, :to_s, {}, class: "form-control" %>
    <% if course_was_invalid %>
      <% post.errors.full_messages_for(:course).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% professor_class = "form-control" %>
    <% professor_was_invalid = post.errors.include?(:professor) %>

    <% if was_validated %>
      <% if professor_was_invalid %>
        <% professor_class << " is-invalid" %>
      <% else %>
        <% professor_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :professor_id %>
    <%= f.collection_select :professor_id, Professor.all, :id, :to_s, {}, class: "form-control" %>
    <% if professor_was_invalid %>
      <% post.errors.full_messages_for(:professor).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/posts/_list_item.html.erb
<%= link_to post, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= post %>
    <small class="text-muted">
      <%= time_ago_in_words(post.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/posts/_posts_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "posts_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :rating, "Rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :rating_gteq, :class => "form-control", :placeholder => "Rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :rating_lteq, :class => "form-control", :placeholder => "Rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :course_name_cont, "Course name contains" %>
    <%= f.text_field :course_name_cont, :class => "form-control", :placeholder => "Course name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :poster_name_cont, "Poster name contains" %>
    <%= f.text_field :poster_name_cont, :class => "form-control", :placeholder => "Poster name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :professor_name_cont, "Professor name contains" %>
    <%= f.text_field :professor_name_cont, :class => "form-control", :placeholder => "Professor name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/posts" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#posts_filters">
  Show filters
</a>

app/views/posts/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Post #<%= @post.id %>
      </h2>

      <div class="card-body">
        <%= render "form", post: @post %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Posts

      <%= link_to new_post_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "posts/posts_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Posts

        <%= link_to new_post_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @posts, partial: "list_item", as: :post %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @posts, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Post
      </h2>

      <div class="card-body">
        <%= render "form", post: @post %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @post, partial: "card", as: :post %>
  </div>
</div>